package hu.test.lottery;

/**
 * The implementation of Random interface. DO NOT EDIT THIS FILE.
 */
public class RandomImpl implements Random {

    public int nextInt() {
        return new java.util.Random().nextInt();
    }
}
